### ISSUE TITLE
Better description of blackOutPeriod 

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#84]
Probably not familar to most (including me!) so would be good to have a slightly more detailed description of what it means
https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/166cb5c1991639ba5b8633a966e3c4dd3b1a162c/R/getCohortSequence.R#L24

**Comment by daniellenewby** [comment]
see this paper:
https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y

The blackout period (also called ‘time-lag period’ and ‘lag time’) is the period immediately after the initiation of the first medication in which events, i.e. the start of the other medication, will not be taken into account. Such a period is relevant to ensure sufficient time for the development of the ADR induced by the index medication and subsequent treatment with the marker medication [[17](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#ref-CR17)]. Singh et al. studied the prescribing cascade of calcium channel blocker (CCB)-induced edema treated with diuretics [[17](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#ref-CR17)]. They imposed a blackout period of 7 days because the probability of developing edema within 7 days after initiating CCBs is low. Other studies mentioned that patients need to be excluded if they have their first prescription of the index and marker medication on the exact same date, as the sequence of the index and marker medication cannot be extracted (see Fig. [3](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#Fig3), example C) [[7](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#ref-CR7), [8](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#ref-CR8)]. Formally, this is not defined as blackout period but is important to address as exclusion criterion. Although an ADR may occur immediately, it seems impossible that a prescribing cascade occurs on the day of the first prescription.

**Comment by catalamarti** [comment]
and maybe rename

**Comment by xihang-chen** [comment]
merged this together with timeGap #85
