### ISSUE TITLE
rename timeGap

### ISSUE THREAD

**Issue by edward-burn** [oxford-pharmacoepi/CohortSymmetry#85]
We have the same name in CohortSurvival but there it means something completely different https://github.com/oxford-pharmacoepi/CohortSymmetry/blob/166cb5c1991639ba5b8633a966e3c4dd3b1a162c/R/getCohortSequence.R#L29

Instead of a single value should it be a min and max (e.g. 0 to Inf)?

**Comment by daniellenewby** [comment]
According to review [here ](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y)- this is called exposure window. It is a single value not a range.

The exposure window (also called ‘exposure time window’ or ‘observation period’) is the defined follow-up period to capture the pairs of incident index and marker medication users and vice versa, so the maximum allowed time period between the start of the index and the start of the marker medication [[20](https://bmcmedresmethodol.biomedcentral.com/articles/10.1186/s12874-023-02108-y#ref-CR20)]. The exposure window should depend on the expected time onset of the ADR caused by the index medication

**Comment by KimLopezGuell** [comment]
Just as an update to this from CohortSurvival, now that input name has been changed there to eventGap

**Comment by edward-burn** [comment]
check input, value 1 must be 0 or above. value 2 must be the same or greater than value 1

**Comment by edward-burn** [comment]
default: c(0, 365)
